### ISSUE TITLE
PSGD vs Adam

### ISSUE THREAD

**Issue by Oussamab21** [lixilinx/psgd_tf#1]
Hi thank you for sharing this great work ; I had a question can the PSGD perform better then Adam algorithm when used for 3D object detection using CNN ?
Thank you

**Comment by lixilinx** [comment]
You need to try to find it out. My experiences on real world data suggest that Adam is very close to RMSProp. The order looks like: PSGD with kron > PSGD with scan > PSGD with diag = Adam = RMSProp.   

Note that I skipped Adam here to keep comparison simple. Adam basically is RMSProp + momentum. All methods in our comparisons do not use momentum, and all methods could benefit from gradient moving average. It will be interesting to see what is the gain after combining PSGD and momentum (traditional or Nesterov momentum, precondition the moving averaged gradient or moving average the preconditioned gradient). On these benchmark problems, Adam is close to RMSProp, and their differences are far less than the differences between RMSProp and PSGD with kron preconditioner.
