### ISSUE TITLE
time per iteration by PSGD 

### ISSUE THREAD

**Issue by usmanqadeer1** [lixilinx/psgd_tf#2]
PSGD works great for the mentioned examples for it converges in lesser number of iterations as well as lesser time. But for models with large number of parameters, one iteration of PSGD would take a lot more time than that of first order methods i.e. SGD, RMSprop and ADAM. Is there a solution for models with large number of parameters?

**Comment by lixilinx** [comment]
That depends on the selection of preconditioner. If you choose it properly, one iteration of PSGD should be about two times expensive as SGD. So as long as PSGD doubles the convergence speed, there is no loss of performance.   

Suppose that one parameter is a (1000000, 1) vector. Then, a Kronecker preconditioner is really a bad choice, but you should use the normalization preconditioner (batch normalization is a special example of such preconditioner). Please check paper https://openreview.net/forum?id=Bye5SiAqKX for the language model example, where the parameter matrix is a huge matrix, and PSGD with normalization preconditioner still accelerate the convergence considerably.

**Comment by lixilinx** [comment]
By the way, one has no need to update the preconditioner at every iteration. I would update it less and less frequently with the increase of number of iterations since curvature changes slower than gradient. Then asymptotically, PSGD can be as cheap as SGD.
