### ISSUE TITLE
tensorflow 2 support?

### ISSUE THREAD

**Issue by wkirgsn** [lixilinx/psgd_tf#3]
Hi,
thank you for this rigorous repo, the paper was delighting as well.
Today, first-order derivative optimizers are still prevalent in the landscape of automatic differentation frameworks (except for l-bfgs in pytorch, which is missing in tensorflow).
In my research, I happen to be bound on small scale recurrent neural networks (with less than 1000 parameters), and the usual Adam optimizer is not converging satisfactorily on my data exhibiting very long sequences.
This PSGD seems to be promising, yet I have my full framework running on TF2.3.
Is there going to be a TF2 version of the PSGD, and if not, is there any chance to get hints how to tackle this?
Thanks in advance and best regards

**Comment by lixilinx** [comment]
Thanks for the interests. Yes, PSGD with dense preconditioner will work very well for small problems with < 10K parameters. 

I switched to Pytorch for some time. Later learned that TF2.0 also support eager execution, so will be similar to Pytorch or Chain. Maybe the torch and numpy implementations of PSGD are helpful to you (https://github.com/lixilinx/psgd_torch, https://github.com/lixilinx/psgd_np)?  Add this to my todo list, although no definite plan yet.

**Comment by lixilinx** [comment]
I do get a chance to migrate to tf 2.x, and also significantly simplified the usage of Kronecker product preconditioners. Feedbacks are welcome if there is any issue.
